### ISSUE TITLE
The game doesn't run on my PC

### ISSUE THREAD

**Issue by hugo-sna** [megumumpkin/WickedEngine-Demo#10]
When I launch the it instantly crashes, there are no error messages.

My hardware:
CPU: Intel core i5 6600
GPU Nvidia GTX 960
RAM: 16GB DDR4

**Comment by megumumpkin** [comment]
What's the operating system that you're using on that system?

**Comment by hugo-sna** [comment]
I'm using Windows 10, I just downloaded the game unzipped it and ran RUN_DEMO.bat

**Comment by hugo-sna** [comment]
Do I need some kind of devtools to run it?

**Comment by megumumpkin** [comment]
No
Currently working on the fix, please wait

**Comment by megumumpkin** [comment]
Can you test this one?
[https://github.com/megumumpkin/WickedEngine-Demo/releases/download/v2023.2-prealpha/PlayerCharacterDemo-Windows-Fix1Test.zip](https://github.com/megumumpkin/WickedEngine-Demo/releases/download/v2023.2-prealpha/PlayerCharacterDemo-Windows-Fix1Test.zip)

**Comment by hugo-sna** [comment]
Thanks, it works now

**Comment by megumumpkin** [comment]
Thanks for the report! Look forward for further development or if you like, you can contribute even further by joining WickedEngine's discord forum (esp. in the `game-demo-development` channel)
