### ISSUE TITLE
Build/Data/Shader is not a directory

### ISSUE THREAD

**Issue by SeleDreams** [megumumpkin/WickedEngine-Demo#6]
Hi, I've been trying to build this repository using the build.sh and build.py (tried both) however in both cases while the code successfully built, I end up with this Build/Data/Shader is not a directory error around the end, it seems like the Shader directory is missing from the Data folder
I can't tell if it's something that was supposed to get built during compilation or not

**Comment by megumumpkin** [comment]
Ah yeah, those build scripts aren't ported yet, you can build through vscode though.

**Comment by megumumpkin** [comment]
Install the CMake plugin and build from there first.
I'll try to resolve this.

**Comment by megumumpkin** [comment]
Can I see the full terminal log when you're building this (on both build.sh and build.py)?

**Comment by MolassesLover** [comment]
That's weird, it might've been a mistake on my end. Does running this command work out?
```sh
cmake -B Build && cmake --build Build -j$(nproc)
```

**Comment by SeleDreams** [comment]
> That's weird, it might've been a mistake on my end. Does running this command work out?
> 
> ```shell
> cmake -B Build && cmake --build Build -j$(nproc)
> ```

seledreams@seledreams-Predator-PH315-51:~/development/WickedEngine-Demo$ cmake -B Build && cmake --build Build -j$(nproc)
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so  
OpenImageDenoise not found, it will be disabled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/seledreams/development/WickedEngine-Demo/Build
[  4%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/Debug.cpp.o
[  4%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/DirectorySnapshot.cpp.o
[  6%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/DirectorySnapshotDiff.cpp.o
[  8%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/FileSystem.cpp.o
[ 10%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/DirWatcherGeneric.cpp.o
[ 12%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/FileWatcher.cpp.o
[ 16%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/FileWatcherGeneric.cpp.o
[ 16%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/FileInfo.cpp.o
[ 18%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/FileWatcherCWrapper.cpp.o
[ 20%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/FileWatcherImpl.cpp.o
[ 22%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/Log.cpp.o
[ 24%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/Mutex.cpp.o
[ 26%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/String.cpp.o
[ 28%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/System.cpp.o
[ 30%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/Watcher.cpp.o
[ 32%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/Thread.cpp.o
[ 34%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/WatcherGeneric.cpp.o
[ 36%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/platform/posix/FileSystemImpl.cpp.o
[ 38%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/platform/posix/MutexImpl.cpp.o
[ 40%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/platform/posix/SystemImpl.cpp.o
[ 42%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/FileWatcherInotify.cpp.o
[ 44%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/platform/posix/ThreadImpl.cpp.o
[ 46%] Building CXX object Library/efsw/CMakeFiles/efsw.dir/src/efsw/WatcherInotify.cpp.o
[ 48%] Linking CXX shared library libefsw.so
[ 48%] Built target efsw
[ 55%] Building CXX object CMakeFiles/Dev.dir/Source/Resources_BindLua.cpp.o
[ 57%] Building CXX object CMakeFiles/Dev.dir/Source/RenderPipeline.cpp.o
[ 57%] Building CXX object CMakeFiles/Dev.dir/Source/Resources.cpp.o
[ 65%] Building CXX object CMakeFiles/Game.dir/Source/Resources_BindLua.cpp.o
[ 65%] Building CXX object CMakeFiles/Game.dir/Source/LiveUpdate.cpp.o
[ 65%] Building CXX object CMakeFiles/Game.dir/Source/Resources.cpp.o
[ 65%] Building CXX object CMakeFiles/Game.dir/Source/main_SDL2.cpp.o
[ 61%] Building CXX object CMakeFiles/Dev.dir/Source/BindLua.cpp.o
[ 69%] Building CXX object CMakeFiles/Game.dir/Source/Game.cpp.o
[ 69%] Building CXX object CMakeFiles/Game.dir/Source/BindLua.cpp.o
[ 71%] Building CXX object CMakeFiles/Game.dir/Source/RenderPipeline.cpp.o
[ 73%] Building CXX object CMakeFiles/Dev.dir/Source/LiveUpdate.cpp.o
[ 75%] Building CXX object CMakeFiles/Dev.dir/Source/Game.cpp.o
[ 77%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/imgui.cpp.o
[ 79%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/imgui_demo.cpp.o
[ 81%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/imgui_draw.cpp.o
[ 83%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/imgui_tables.cpp.o
[ 85%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/imgui_widgets.cpp.o
[ 87%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/imgui_impl_sdl.cpp.o
[ 89%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/imgui_BindLua.cpp.o
[ 91%] Building CXX object CMakeFiles/Dev.dir/Source/ImGui/Widgets/ImGuizmo.cpp.o
[ 93%] Building CXX object CMakeFiles/Dev.dir/Source/Editor.cpp.o
[ 95%] Building CXX object CMakeFiles/Dev.dir/Source/main_SDL2.cpp.o
[ 97%] Linking CXX executable Game
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_Text(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:677:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
  677 | CALL_FUNCTION_NO_RET(Text, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_TextColored(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:686:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
  686 | CALL_FUNCTION_NO_RET(TextColored, col, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_TextDisabled(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:694:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
  694 | CALL_FUNCTION_NO_RET(TextDisabled, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_TextWrapped(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:702:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
  702 | CALL_FUNCTION_NO_RET(TextWrapped, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_LabelText(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:711:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
  711 | CALL_FUNCTION_NO_RET(LabelText, label, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_BulletText(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:719:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
  719 | CALL_FUNCTION_NO_RET(BulletText, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_TreeNode_3(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:270:30: warning: format not a string literal and no format arguments [-Wformat-security]
  270 |     retType ret = ImGui::name(__VA_ARGS__);
      |                   ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:1195:1: note: in expansion of macro ‘CALL_FUNCTION’
 1195 | CALL_FUNCTION(TreeNode, bool, str_id, fmt)
      | ^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_TreeNode_3_3(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:270:30: warning: format not a string literal and no format arguments [-Wformat-security]
  270 |     retType ret = ImGui::name(__VA_ARGS__);
      |                   ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:1204:1: note: in expansion of macro ‘CALL_FUNCTION’
 1204 | CALL_FUNCTION(TreeNode, bool, ptr_id, fmt)
      | ^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_TreeNodeEx_4(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:270:30: warning: format not a string literal and no format arguments [-Wformat-security]
  270 |     retType ret = ImGui::name(__VA_ARGS__);
      |                   ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:1225:1: note: in expansion of macro ‘CALL_FUNCTION’
 1225 | CALL_FUNCTION(TreeNodeEx, bool, str_id, flags, fmt)
      | ^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_TreeNodeEx_4_4(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:270:30: warning: format not a string literal and no format arguments [-Wformat-security]
  270 |     retType ret = ImGui::name(__VA_ARGS__);
      |                   ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:1234:1: note: in expansion of macro ‘CALL_FUNCTION’
 1234 | CALL_FUNCTION(TreeNodeEx, bool, ptr_id, flags, fmt)
      | ^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_SetTooltip(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:1427:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
 1427 | CALL_FUNCTION_NO_RET(SetTooltip, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h: In function ‘int impl_LogText(lua_State*)’:
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_BindLua.cpp:276:16: warning: format not a string literal and no format arguments [-Wformat-security]
  276 |     ImGui::name(__VA_ARGS__);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~
/home/seledreams/development/WickedEngine-Demo/Source/ImGui/imgui_iterator.h:1718:1: note: in expansion of macro ‘CALL_FUNCTION_NO_RET’
 1718 | CALL_FUNCTION_NO_RET(LogText, fmt)
      | ^~~~~~~~~~~~~~~~~~~~
Error: Target (for copy_if_different command) "/home/seledreams/development/WickedEngine-Demo/Build/Data/Shader/" is not a directory.
gmake[2]: *** [CMakeFiles/Game.dir/build.make:203 : Game] Erreur 1
gmake[2]: *** Suppression du fichier « Game »
gmake[1]: *** [CMakeFiles/Makefile2:117 : CMakeFiles/Game.dir/all] Erreur 2
gmake[1]: *** Attente des tâches non terminées....
[100%] Linking CXX executable Dev
[100%] Built target Dev
gmake: *** [Makefile:136 : all] Erreur 2

**Comment by megumumpkin** [comment]
Now the build script does not copy the build folder, instead left it as is from the previous task done by the cmake itself, which symlinks the Data folder to the one within Build folder.
